# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\utilitarios_e_programas\Projetos VSCode - Python\CPF\Design_CPF.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Validador_Gerador_de_CPF(object):
    def setupUi(self, Gerador_Validador_CPF):
        Gerador_Validador_CPF.setObjectName("Gerador_Validador_CPF")
        Gerador_Validador_CPF.setGeometry(QtCore.QRect(0, 0, 403, 152))
        self.centralwidget = QtWidgets.QWidget(Gerador_Validador_CPF)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 11, 102, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputValidaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCPF.setGeometry(QtCore.QRect(120, 12, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputValidaCPF.setFont(font)
        self.inputValidaCPF.setObjectName("inputValidaCPF")
        self.btn_valida = QtWidgets.QPushButton(self.centralwidget)
        self.btn_valida.setGeometry(QtCore.QRect(298, 11, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_valida.setFont(font)
        self.btn_valida.setObjectName("btn_valida")
        self.btn_gerar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gerar.setGeometry(QtCore.QRect(298, 48, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setObjectName("btn_gerar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 50, 87, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Retorno = QtWidgets.QLabel(self.centralwidget)
        self.Retorno.setGeometry(QtCore.QRect(10, 90, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Retorno.setFont(font)
        self.Retorno.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Retorno.setText("")
        self.Retorno.setAlignment(QtCore.Qt.AlignCenter)
        self.Retorno.setObjectName("Retorno")
        Gerador_Validador_CPF.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gerador_Validador_CPF)
        QtCore.QMetaObject.connectSlotsByName(Gerador_Validador_CPF)

    def retranslateUi(self, Gerador_Validador_CPF):
        _translate = QtCore.QCoreApplication.translate
        Gerador_Validador_CPF.setWindowTitle(_translate("Validador_Gerador_de_CPF", "MainWindow"))
        self.label_2.setText(_translate("Validador_Gerador_de_CPF", "VALIDAR CPF"))
        self.btn_valida.setText(_translate("Validador_Gerador_de_CPF", "VALIDAR"))
        self.btn_gerar.setText(_translate("Validador_Gerador_de_CPF", "GERAR"))
        self.label.setText(_translate("Validador_Gerador_de_CPF", "GERAR CPF"))
