# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_cpf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 152)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 11, 102, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputValidaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCPF.setGeometry(QtCore.QRect(120, 12, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputValidaCPF.setFont(font)
        self.inputValidaCPF.setObjectName("inputValidaCPF")
        self.btn_valida = QtWidgets.QPushButton(self.centralwidget)
        self.btn_valida.setGeometry(QtCore.QRect(298, 11, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_valida.setFont(font)
        self.btn_valida.setObjectName("btn_valida")
        self.btn_gerar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gerar.setGeometry(QtCore.QRect(298, 48, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setObjectName("btn_gerar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 50, 87, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Retorno = QtWidgets.QLabel(self.centralwidget)
        self.Retorno.setGeometry(QtCore.QRect(10, 90, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Retorno.setFont(font)
        self.Retorno.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Retorno.setText("")
        self.Retorno.setAlignment(QtCore.Qt.AlignCenter)
        self.Retorno.setObjectName("Retorno")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "VALIDAR CPF"))
        self.btn_valida.setText(_translate("MainWindow", "VALIDAR"))
        self.btn_gerar.setText(_translate("MainWindow", "GERAR"))
        self.label.setText(_translate("MainWindow", "GERAR CPF"))
